# D-Flat Test Suite Makefile
# For TinyCC (x64 Windows)

CC = c:\tcc\tcc.exe
CFLAGS = -I.
LDFLAGS = -lkernel32 -luser32

test.exe: test_main.obj test_rect.obj test_keys.obj rect_test.obj keys_test.obj test_tcccompat.obj test_tccwin32.obj test_console.obj test_message.obj test_video.obj test_mouse.obj test_direct.obj test_df_test.obj ..\tinycc\tccwin32.obj ..\win32\console_win32.obj
	$(CC) -o test.exe test_main.obj test_rect.obj test_keys.obj rect_test.obj keys_test.obj test_tcccompat.obj test_tccwin32.obj test_console.obj test_message.obj test_video.obj test_mouse.obj test_direct.obj test_df_test.obj ..\tinycc\tccwin32.obj ..\win32\console_win32.obj $(LDFLAGS)

# test_main.c must be compiled with DF_TEST_IMPLEMENTATION
test_main.obj: test_main.c df_test.h
	$(CC) $(CFLAGS) -DF_TEST_IMPLEMENTATION -c -o test_main.obj test_main.c

test_rect.obj: test_rect.c df_test.h test_dflat.h
	$(CC) $(CFLAGS) -c -o test_rect.obj test_rect.c

test_keys.obj: test_keys.c df_test.h test_dflat.h
	$(CC) $(CFLAGS) -c -o test_keys.obj test_keys.c

rect_test.obj: rect_test.c test_dflat.h
	$(CC) $(CFLAGS) -c -o rect_test.obj rect_test.c

keys_test.obj: keys_test.c test_dflat.h
	$(CC) $(CFLAGS) -c -o keys_test.obj keys_test.c

test_tcccompat.obj: test_tcccompat.c df_test.h
	$(CC) $(CFLAGS) -c -o test_tcccompat.obj test_tcccompat.c

test_tccwin32.obj: test_tccwin32.c df_test.h
	$(CC) $(CFLAGS) -c -o test_tccwin32.obj test_tccwin32.c

test_console.obj: test_console.c df_test.h
	$(CC) $(CFLAGS) -c -o test_console.obj test_console.c

test_message.obj: test_message.c df_test.h
	$(CC) $(CFLAGS) -c -o test_message.obj test_message.c

test_video.obj: test_video.c df_test.h
	$(CC) $(CFLAGS) -I.. -c -o test_video.obj test_video.c

test_mouse.obj: test_mouse.c df_test.h
	$(CC) $(CFLAGS) -I.. -c -o test_mouse.obj test_mouse.c

test_direct.obj: test_direct.c df_test.h
	$(CC) $(CFLAGS) -I.. -c -o test_direct.obj test_direct.c

test_df_test.obj: test_df_test.c df_test.h
	$(CC) $(CFLAGS) -c -o test_df_test.obj test_df_test.c


..\tinycc\tccwin32.obj: ..\tinycc\tccwin32.c ..\tinycc\tccwin32.h
	$(CC) $(CFLAGS) -c -o $@ $<

..\win32\console_win32.obj: ..\win32\console_win32.c ..\console.h ..\tinycc\tcccompat.h ..\tinycc\tccwin32.h
	$(CC) $(CFLAGS) -I.. -c -o $@ $<

run: test.exe
	@.\test.exe
	@echo Tests passed!

clean:
	del /Q *.obj test.exe

.PHONY: run clean